# Horizontal Pod Autoscaler for cache-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tick12-cache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tick12-cache-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80